language: java
java:
  - "Oracle JDK 8"
sudo: false
before_install: mvn test
install: nmvn install
##before_script: grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
