language: java
jdk:
  - oraclejdk8
sudo: false
before_install: mvn test
install: mvn install
##before_script: grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
